### ISSUE TITLE
QRTE Parser Code Issues

### ISSUE THREAD

**Issue by jshropsh73** [ErwinHaasnoot/qrteparser-webservice#2]
Hello! 

I am having issues running my data using the parser python file. I tried running this with a mac and a pc and it didn't work on either device. My friend who previously processed her data file using the parser ran the same file again and got a similar error message. I have pasted the error message below. I get this error message for every single participant. If you have any insight I would greatly appreciate it, thanks! 

[/Users/jessicashropshire1/SocialVisionPsychTools/qrteparser-webservice/qrte_parser_python/qrtemarkupnode.py:346] [ERROR] [CODE:4][TAG:ERR_COLUMN_INVALID_JSON] Subject: R_Tc1yjGjaZiFrcqt, Data: , SubjectId: 42 - Column cache is not valid JSON. Likely that respondent quit the survey early. If this is not the case, please report immediately to support@qrtengine.com, with the survey .qsf and the original data file.

**Comment by ErwinHaasnoot** [comment]
Hi jshropsh73,

This seems like the same issue Becky Gilbert reported. I'm looking at that right now.

**Comment by ErwinHaasnoot** [comment]
Which is the following: https://github.com/ErwinHaasnoot/qrteparser-webservice/issues/1

**Comment by jshropsh73** [comment]
Sorry to bug again, but my embedded data columns in my data file are empty. Does this mean that I can't parse the current data file I have at all? 

If you have a bug-free version of the parser file, is there any way you can look at it specifically for the data file I am using? I have e-mailed you a copy of the data file as it will not allow me to upload it here. I just want to make sure it is indeed a programming issue and not something I'm doing wrong.

**Comment by ErwinHaasnoot** [comment]
Hi,

Yes :( Im afraid the embedded data wasnt saved, so there's nothing for the
parser to work with..

**Comment by ErwinHaasnoot** [comment]
Actually, sorry that's not true. The 4 embedded data fields are for context
and only need to be generated once. You can run through the survey again
with the jfe fix enabled and take the QRTE_\* embedded data fields of that
run and copy it to the ones lacking it  Parsing should work again after.
that

**Comment by jshropsh73** [comment]
Great, thank you! 

Jessica Shropshire 
PhD Student
Social Psychology 
University of California, Los Angeles 
Email: jshropsh@g.ucla.edu

**Comment by jshropsh73** [comment]
I tried running the code using your above recommendation (run the survey again with the fix and copy the ones lacking it) and I still get this error message

jessica-shropshires-macbook:qrteparser-webservice jessicashropshire1$ python parser.py ~/documents/sexyscientist/mf_sh_iat_faces.csv
Traceback (most recent call last):
  File "parser.py", line 5, in <module>
    from qrte_parser_python import QRTEParser, QRTEParserLogger, log
  File "/Users/jessicashropshire1/qrteparser-webservice/qrte_parser_python/**init**.py", line 5, in <module>
    from .qrteparser import QRTEParser
  File "/Users/jessicashropshire1/qrteparser-webservice/qrte_parser_python/qrteparser.py", line 2, in <module>
    from builtins import object
ImportError: No module named builtins
jessica-shropshires-macbook:qrteparser-webservice jessicashropshire1$

**Comment by lindsayhinzman** [comment]
Hello, 

I've come across the same error mentioned above, "ImportError: No module named builtins".

Do you know the cause of this error message? I don't think its an issue with my datafile, because I am having the same issue with a previous file I previously parsed. 

Thank you!
Lindsay

**Comment by psychological** [comment]
Hi Erwin,

The same error message ("ImportError: No module named builtins") is appearing for me as well. 

An older version of the qrteparser-webservice was able to run without this error message but it was leaving me with no data for the Stroop trials (even though I can see that the data is there in the raw .csv file). I decided to download the newest qrteparser-webservice to see if it would solve this problem but I can't even get it to run due to this error message. 

Any help would be appreciated.

Thanks,
Colin

**Comment by psychological** [comment]
Hi Erwin,

Just wondering if you had a chance to investigate why this error message is appearing for the new parser and/or why the old parser is not converting the Stroop data properly.

Thanks,
Colin

**Comment by ErwinHaasnoot** [comment]
Hi,

I'm just going over all the old issues.. this was due to a missing requirement (builtins) in the requirements.txt file. Installing this separately would have fixed it, but I have removed the need for it altogether in the newest version parser.
